import {refreshPs,renderPs,psSnapshot} from './ps-ui.mjs';
import {model,report} from './model.mjs';
const SHEET='1RzhVHTJQOI6f1Iv1VL7-_wt6oB7TksVANdEcEIzcbSI';
const $=id=>document.getElementById(id),fmt=(n,d=0)=>new Intl.NumberFormat('vi-VN',{maximumFractionDigits:d}).format(n),escape=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let data,lastSuccess;let seq=0;
$('source').href=`https://docs.google.com/spreadsheets/d/${SHEET}/edit`;
$('unit').value='million';
function readSheet(name){return new Promise((resolve,reject)=>{const cb='sheetCallback'+(++seq),script=document.createElement('script');let done=false;const timer=setTimeout(()=>finish(Error('Google Sheets phản hồi quá lâu. Vui lòng thử cập nhật lại.')),25000);function finish(err,result){if(done)return;done=true;clearTimeout(timer);script.remove();delete window[cb];err?reject(err):resolve(result)}window[cb]=r=>{if(r.status!=='ok'||!r.table)return finish(Error('Không đọc được sheet '+name+'. Kiểm tra quyền xem của link Google Sheets.'));finish(null,[r.table.cols.map(c=>c.label),...r.table.rows.map(r=>r.c.map(c=>c?.v??null))])};script.onerror=()=>finish(Error('Không kết nối được Google Sheets. Kiểm tra mạng và quyền xem của sheet.'));script.src=`https://docs.google.com/spreadsheets/d/${SHEET}/gviz/tq?sheet=${encodeURIComponent(name)}&headers=1&tqx=${encodeURIComponent('out:json;responseHandler:'+cb)}&_=${Date.now()}`;document.head.append(script)})}
function options(id,items,all){const prev=$(id).value;$(id).innerHTML=(all?`<option value="">${escape(all)}</option>`:'')+items.map(v=>`<option value="${escape(v)}">${escape(v)}</option>`).join('');if([...$(id).options].some(o=>o.value===prev))$(id).value=prev;$(id).disabled=false;}
function periods(){const available=data.periods.filter(p=>p.split('-')[0]===$('year').value);options('period',available);const latest=data.purchases.map(p=>p.period).filter(p=>available.includes(p)).sort().at(-1);$('period').value=latest||available[0]||'';}
function filters(){return {period:$('period').value,region:$('region').value,fsm:$('fsm').value,level:$('level').value,outlet:$('outlet').value,search:$('search').value,price:$('price').value,unit:$('unit').value,mode:'cumulative'}}
function render(){if(!data)return;renderPs(data,filters());const f=filters(),r=report(data,f);const cumulative=f.mode==='cumulative';$('periodtitle').textContent='REPORT ON TRADE PROGRAM';
 const cards=[['Tổng số Outlet',fmt(r.totalOutlets),'Số lượng Outlet tham gia'],['Target Phasing total',fmt(r.targetTotal,2),'Triệu đồng · toàn bộ chương trình'],['Target Phasing lũy kế',fmt(r.plan,2),`Triệu đồng · ${r.startPeriod} → ${f.period}`],['Total Performance lũy kế',fmt(r.amount/1e6),'Giá 110'],['% đạt Plan',r.achievement===null?'—':fmt(r.achievement*100,1)+'%','Actual lũy kế / Target lũy kế'],['% đạt total',r.targetTotal>0?fmt(r.amount/1e6/r.targetTotal*100,1)+'%':'—','Actual lũy kế / Target Phasing total']];
 $('kpis').innerHTML=cards.map(([label,value,note])=>`<article><span>${label}</span><strong>${value}</strong>${note?`<small>${note}</small>`:''}</article>`).join('');
 const months=cumulative?data.periods.filter(p=>p<=f.period):data.periods.filter(p=>p.startsWith($('year').value+'-'));
 const points=months.map(period=>({...report(data,{...f,period,mode:'month'}),period}));
 const max=Math.max(1,...points.map(p=>p.amount));
 const yearGroups=[];
 points.forEach((p,index)=>{const year=p.period.split('-')[0];const last=yearGroups.at(-1);if(last?.year===year)last.count++;else yearGroups.push({year,start:index+1,count:1});});
 $('chart').innerHTML=`<div class="chart-grid" style="grid-template-columns:repeat(${Math.max(1,points.length)},minmax(67px,1fr))">${points.map((p,index)=>`<div class="barcol ${p.period===f.period?'selected':''}" style="grid-column:${index+1};grid-row:1" title="${p.period}: ${fmt(p.amount)} đồng"><span class="barvalue">${fmt(p.amount/1e6,1)}</span><div class="bar" style="height:${Math.max(1,p.amount/max*155)}px"></div><span>${p.period.split('-')[1]}</span></div>`).join('')}${yearGroups.map(g=>`<div class="chart-year" style="grid-column:${g.start} / span ${g.count};grid-row:2">${g.year}</div>`).join('')}</div>`;
 $('coverage').innerHTML=`<div class="bigcoverage">${r.coverage===null?'—':fmt(r.coverage*100,1)+'%'}</div><div class="muted" style="font-size:.875rem">OL có Plan đã phát sinh mua hàng</div><div class="track"><i style="width:${(r.coverage??0)*100}%"></i></div><div class="coverrow"><span>Đã mua / Có Plan</span><b>${r.bought} / ${r.planned}</b></div><div class="coverrow"><span>Chưa phát sinh mua</span><b>${r.planned-r.bought}</b></div><div class="coverrow"><span>Mua ngoài Plan kỳ này</span><b>${r.unplanned}</b></div>`;
 $('rowcount').textContent=`${r.rows.length} outlet · ${cumulative?r.startPeriod+' → ':''}${f.period} · Đơn vị: VND · Giá 110`;
 $('rows').innerHTML=r.rows.sort((a,b)=>b.amount-a.amount).map(o=>`<tr><td><b>${escape(o.name)}</b><small>${escape(o.code)}</small></td><td>${escape(o.region)}<small>${escape(o.fsm)}</small></td><td>${escape(o.level)}</td><td>${o.onList?fmt(o.targetTotal*1e6):'—'}</td><td>${o.plan===null?'—':fmt(o.plan*1e6)}</td><td><b>${fmt(o.amount)}</b></td><td>${o.achievement===null?'—':fmt(o.achievement*100,1)+'%'}</td><td>${o.totalAchievement===null?'—':fmt(o.totalAchievement*100,1)+'%'}</td><td><span class="pill ${o.plan===null?'':o.transactions?'yes':'wait'}">${o.plan===null?'Ngoài Plan':o.transactions?'Đã mua':'Chưa mua'}</span></td></tr>`).join('')||'<tr><td colspan="9" class="empty">Không có outlet phù hợp với bộ lọc.</td></tr>';
 $('quality').textContent=`Đã đọc ${data.outlets.filter(o=>o.onList).length} OL trong On_list và ${data.sourceRows} dòng mua hàng. ${data.invalidPeriods} dòng bị loại do kỳ F/P trống hoặc không hợp lệ; ${data.missingCodes} dòng mua hàng thiếu mã. Các dòng mua hàng được cộng nguyên theo nguồn, không tự xóa dòng giống nhau.`;
}
async function refresh(){if($('refresh').disabled)return;refreshPs(()=>[data,filters()]);$('refresh').disabled=true;$('refresh').textContent='Đang cập nhật…';try{const [p,b]=await Promise.all([readSheet('On_list'),readSheet('ONT mua hàng')]);const next=model(p,b);if(!next.periods.length)throw Error('Không tìm thấy kỳ F/P trong dữ liệu.');data=next;options('year',[...new Set(data.periods.map(p=>p.split('-')[0]))]);const latest=data.purchases.map(p=>p.period).sort().at(-1)||data.periods[0];$('year').value=latest.split('-')[0];periods();$('period').value=latest;options('region',[...new Set(data.outlets.map(o=>o.region))].sort(),'Tất cả vùng');options('fsm',[...new Set(data.outlets.map(o=>o.fsm))].sort(),'Tất cả FSM');options('level',[...new Set(data.outlets.filter(o=>o.onList).map(o=>o.level))].sort(),'Tất cả Level');const prevOutlet=$('outlet').value;$('outlet').innerHTML='<option value="">Tất cả Outlet</option>'+data.outlets.slice().sort((a,b)=>a.name.localeCompare(b.name,'vi')).map(o=>`<option value="${escape(o.key)}">${escape(o.name)}</option>`).join('');if(data.outlets.some(o=>o.key===prevOutlet))$('outlet').value=prevOutlet;lastSuccess=new Date();$('synctime').textContent='Cập nhật '+lastSuccess.toLocaleString('vi-VN');$('error').hidden=true;render()}catch(e){$('error').hidden=false;$('error').textContent=e.message+(data?' Đang hiển thị dữ liệu lần tải thành công trước.':' Chưa có dữ liệu để tính báo cáo.');$('synctime').textContent=lastSuccess?'Dữ liệu cũ · '+lastSuccess.toLocaleString('vi-VN'):'Chưa kết nối thành công';if(!data)$('rows').innerHTML='<tr><td colspan="9" class="empty">Chưa đọc được dữ liệu. Bấm Cập nhật để thử lại.</td></tr>'}finally{$('refresh').disabled=false;$('refresh').textContent='↻ Cập nhật dữ liệu'}}
$('refresh').addEventListener('click',refresh);$('year').addEventListener('change',()=>{periods();render()});['period','region','fsm','outlet','level','price','unit'].forEach(id=>$(id).addEventListener('change',render));$('search').addEventListener('input',render);
if(document.modelContext?.registerTool){try{Promise.resolve(document.modelContext.registerTool({name:'read_ontrade_report',title:'Đọc báo cáo ONTRADE',description:'Đọc kết quả báo cáo theo bộ lọc đang hiển thị; không thay đổi dữ liệu nguồn.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute:(input)=>{if(!input||typeof input!=='object'||Array.isArray(input)||Object.keys(input).length)throw Error('Công cụ không nhận tham số');if(!data)throw Error('Dữ liệu chưa tải xong');return {filters:filters(),...report(data,filters()),ps:psSnapshot(data,filters()),updatedAt:lastSuccess.toISOString()}}})).catch(()=>{})}catch{}}
refresh();
