const norm=v=>String(v??'').trim().replace(/\s+/g,' ').toUpperCase();
export function decode(v){if('stringValue'in v)return v.stringValue;if('integerValue'in v)return Number(v.integerValue);if('doubleValue'in v)return v.doubleValue;if('booleanValue'in v)return v.booleanValue;if('timestampValue'in v)return v.timestampValue;if('mapValue'in v)return Object.fromEntries(Object.entries(v.mapValue.fields||{}).map(([k,v])=>[k,decode(v)]));if('arrayValue'in v)return(v.arrayValue.values||[]).map(decode);return null;}
export function documents(result){return result.filter(x=>x.document).map(x=>({...Object.fromEntries(Object.entries(x.document.fields||{}).map(([k,v])=>[k,decode(v)])),documentId:x.document.name}));}
export function fiscal(date){const m=String(date??'').match(/^(\d{4})-(\d{2})(?:-(\d{2}))?$/);if(!m||+m[2]<1||+m[2]>12)return null;const y=+m[1],month=+m[2];if(m[3]&&(+m[3]<1||+m[3]>new Date(Date.UTC(y,month,0)).getUTCDate()))return null;return `F${String(y+(month>=7?1:0)).slice(-2)}-P${String((month+5)%12+1).padStart(2,'0')}`;}
export async function readPs(){
 const endpoint='https://firestore.googleapis.com/v1/projects/ontrade-contrated/databases/(default)/documents:runQuery';
 const read=async(name,fields)=>{const structuredQuery={from:[{collectionId:name}],select:{fields:fields.map(fieldPath=>({fieldPath}))}};if(name==='reports')structuredQuery.where={fieldFilter:{field:{fieldPath:'activityType'},op:'EQUAL',value:{stringValue:'PS'}}};const response=await fetch(endpoint,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({structuredQuery}),signal:AbortSignal.timeout(25000)});if(!response.ok)throw Error(`Không đọc được dữ liệu PS (${response.status}).`);const result=await response.json();if(!Array.isArray(result)||result.some(x=>x.error))throw Error('Nguồn PS trả về lỗi.');return documents(result);};
 const [reports,targets,products]=await Promise.all([read('reports',['activityType','outletName','psName','companyProductSales','reportDate']),read('pg_targets',['month','outlet','pg','amount']),read('products',['sku','price'])]);return {reports,targets,products,updatedAt:new Date().toISOString()};
}
export function summarizePs(source,model,filters){
 const match=label=>{const code=String(label??'').match(/\bVNM\d+\b/i)?.[0];const matches=model.outlets.filter(o=>o.onList&&(code?norm(o.code)===norm(code):norm(o.name)===norm(label)));return matches.length===1?matches[0]:null;};
 const allows=(o,label)=>{if(!o&&(filters.region||filters.fsm||filters.level||filters.outlet))return false;return(!filters.region||o?.region===filters.region)&&(!filters.fsm||o?.fsm===filters.fsm)&&(!filters.level||o?.level===filters.level)&&(!filters.outlet||o?.key===filters.outlet)&&(!filters.search||norm((o?.name||label)+' '+(o?.code||'')).includes(norm(filters.search)));};
 const prices=new Map;for(const p of source.products){const k=norm(p.sku),v=Number(p.price);if(!k)continue;if(prices.has(k)&&prices.get(k)!==v)prices.set(k,NaN);else prices.set(k,v);}
 const groups=new Map;let invalidDates=0;const unmatched=new Set,missing=new Set;const start=filters.startPeriod||model.periods[0],end=filters.period;
 const group=(outletLabel,psName)=>{const o=match(outletLabel);if(!o)unmatched.add(outletLabel);if(!allows(o,outletLabel))return null;const key=JSON.stringify([o?.key||norm(outletLabel),norm(psName)]);if(!groups.has(key))groups.set(key,{outlet:o?.name||outletLabel,code:o?.code||'',matched:!!o,psName:psName||'Chưa có tên PS',target:0,hasTarget:false,revenue:0,complete:true,reports:0,dates:new Set});return groups.get(key);};
 const within=date=>{const p=fiscal(date);if(!p){invalidDates++;return false;}return p>=start&&p<=end;};
 for(const t of source.targets){if(!within(t.month))continue;const g=group(t.outlet,t.pg);if(!g)continue;const amount=Number(t.amount);if(!Number.isFinite(amount))throw Error('Chỉ tiêu PS không hợp lệ.');g.target+=amount;g.hasTarget=true;}
 for(const r of source.reports){if(r.activityType!=='PS'||!within(r.reportDate))continue;const g=group(r.outletName,r.psName);if(!g)continue;g.reports++;g.dates.add(r.reportDate);for(const [sku,raw]of Object.entries(r.companyProductSales||{})){const quantity=Number(raw);if(!Number.isFinite(quantity)||quantity<0){g.complete=false;missing.add(sku+' (số lượng không hợp lệ)');continue;}if(quantity===0)continue;const price=prices.get(norm(sku));if(!Number.isFinite(price)||price<0){g.complete=false;missing.add(sku);continue;}g.revenue+=quantity*price;}}
 const rows=[...groups.values()].map(g=>({...g,days:g.dates.size,dates:undefined,achievement:g.complete&&g.target>0?g.revenue/g.target:null})).sort((a,b)=>b.revenue-a.revenue);const target=rows.reduce((s,r)=>s+r.target,0),revenue=rows.reduce((s,r)=>s+r.revenue,0),complete=rows.every(r=>r.complete);
 return {rows,target,revenue,complete,achievement:complete&&target>0&&rows.every(r=>r.hasTarget)?revenue/target:null,missingTargets:rows.filter(r=>!r.hasTarget).length,reportCount:rows.reduce((s,r)=>s+r.reports,0),activePs:new Set(rows.filter(r=>r.reports).map(r=>norm(r.psName))).size,invalidDates,unmatched:[...unmatched],missing:[...missing],start,end,latestPeriod:source.reports.map(r=>fiscal(r.reportDate)).filter(Boolean).sort().at(-1)};
}
