import {readPs,summarizePs,fiscal} from './ps-model.mjs';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmt=(v,d=0)=>new Intl.NumberFormat('en-GB',{maximumFractionDigits:d}).format(v);
let source,loading=false,lastError='';
export function psSnapshot(model,filters){return source?summarizePs(source,model,filters):null;}
export async function refreshPs(getContext){if(loading)return;loading=true;renderPs(...getContext());try{const next=await readPs();source=next;lastError='';}catch(e){lastError=e.message;}finally{loading=false;renderPs(...getContext());}}
export function renderPs(model,filters){const box=document.getElementById('ps-content');if(!box)return;if(!model){box.textContent='Waiting for outlet data…';return;}if(!source){box.textContent=lastError||'Loading PS data from Firebase…';return;}let r;try{r=summarizePs(source,model,filters);}catch(e){box.textContent=e.message;return;}
 const alerts=[r.missingTargets?`${r.missingTargets} PS/outlet entries have no target for this period. Overall achievement is unavailable.`:'',lastError?lastError+' Showing PS data from the previous successful refresh.':'',r.missing.length?'Revenue is incomplete: check SKU/prices for '+r.missing.join(', '):'',r.unmatched.length?'No match in On_list: '+r.unmatched.join(', '):'',r.invalidDates?`${r.invalidDates} rows excluded due to invalid dates or months.`:''].filter(Boolean);
 box.innerHTML=`<p class="muted">Updated ${new Date(source.updatedAt).toLocaleTimeString('en-GB',{timeZone:'Asia/Ho_Chi_Minh',hour12:false})} ${new Date(source.updatedAt).toLocaleDateString('en-GB',{timeZone:'Asia/Ho_Chi_Minh'})}</p>${alerts.map(a=>`<p class="ps-warning" role="status">${esc(a)}</p>`).join('')}<div class="ps-kpis"><article><span>Active PS</span><strong>${r.activePs}</strong></article><article><span>Cumulative PS target</span><strong>${fmt(r.target)}</strong></article><article><span>Cumulative PS revenue${r.complete?'':' (provisional)'}</span><strong>${fmt(r.revenue)}</strong></article><article><span>% PS target achievement</span><strong>${r.achievement===null?'—':fmt(r.achievement*100,1)+'%'}</strong></article></div>${psVisual(model,filters)}${psPivot(r,model,filters)}`;
}

function psVisual(model,filters){
 const points=model.periods.filter(p=>p<=filters.period).map(period=>({...summarizePs(source,model,{...filters,period,startPeriod:period}),period})).filter(x=>x.rows.length>0);
 if(!points.length)return '';
 const max=Math.max(1,...points.flatMap(x=>[x.target,x.revenue]));
 const years=[];points.forEach((p,i)=>{const year=p.period.split('-')[0];const last=years.at(-1);if(last?.year===year)last.count++;else years.push({year,start:i+1,count:1});});
 return `<div class="ps-visual"><div class="ps-vhead"><h3>Monthly PS target & revenue</h3><div class="ps-legend"><span><i class="target"></i>Target</span><span><i class="actual"></i>Revenue</span><span>VND</span></div></div><div class="ps-month-scroll"><div class="ps-month-grid" style="grid-template-columns:repeat(${points.length},minmax(220px,1fr))">${points.map((x,i)=>`<div class="ps-month" style="grid-column:${i+1};grid-row:1"><div class="ps-month-pair"><div class="ps-month-series"><span>${x.rows.some(r=>r.hasTarget)?fmt(x.target):'—'}</span><i class="target" style="height:${x.target/max*165}px" title="Target ${x.period}: ${fmt(x.target)} VND"></i></div><div class="ps-month-series"><span>${fmt(x.revenue)}${x.complete?'':' *'}</span><i class="actual" style="height:${x.revenue/max*165}px" title="Revenue ${x.period}: ${fmt(x.revenue)} VND"></i></div></div><b>${x.period.split('-')[1]}</b><small>${x.achievement===null?'Missing target / data':fmt(x.achievement*100,1)+'% of target'}</small></div>`).join('')}${years.map(y=>`<div class="chart-year" style="grid-column:${y.start} / span ${y.count};grid-row:2">${y.year}</div>`).join('')}</div></div></div>`;
}

function psPivot(total,model,filters){
 const groups=new Map;const key=x=>x.code||x.outlet;
 for(const x of total.rows){const k=key(x);if(!groups.has(k))groups.set(k,{name:x.outlet,code:x.code,rows:[]});groups.get(k).rows.push(x);}
 const months=model.periods.filter(p=>p<=filters.period).map(period=>({period,rows:summarizePs(source,model,{...filters,period,startPeriod:period}).rows}));
 const cells=rows=>{const target=rows.reduce((s,x)=>s+x.target,0),revenue=rows.reduce((s,x)=>s+x.revenue,0);const complete=rows.every(x=>x.complete);const ratio=complete&&rows.every(x=>x.hasTarget)&&target>0?fmt(revenue/target*100,1)+'%':'—';return `<span>${rows.some(x=>x.hasTarget)?fmt(target):'—'}</span><span>${fmt(revenue)}${complete?'':' *'}</span><span>${ratio}</span>`;};
 if(!groups.size)return '<p class="empty">No PS data for the selected filters.</p>';
 return `<div class="ps-pivot-scroll"><div class="ps-pivot"><div class="ps-pivot-head"><span>Outlet / Month / Day</span><span>PS</span><span>PS target (VND)</span><span>PS revenue (VND)</span><span>% PS achievement</span></div>${[...groups.entries()].map(([k,g])=>`<details class="ps-outlet-group"><summary><span class="ps-pivot-name"><b>${esc(g.name)}</b><small>${esc(g.code)}</small></span><span>${esc([...new Set(g.rows.map(x=>x.psName))].join(', '))}</span>${cells(g.rows)}</summary>${months.map(m=>{const rows=m.rows.filter(x=>key(x)===k);if(!rows.length)return '';const dates=[...new Set(source.reports.filter(x=>x.activityType==='PS'&&fiscal(x.reportDate)===m.period).map(x=>x.reportDate))].sort();const days=dates.map(date=>({date,rows:summarizePs({...source,targets:[],reports:source.reports.filter(x=>x.reportDate===date)},model,{...filters,period:m.period,startPeriod:m.period}).rows.filter(x=>key(x)===k)})).filter(d=>d.rows.length);return `<details class="ps-month-group"><summary class="ps-pivot-month"><span>${esc(m.period)}</span><span>${esc([...new Set(rows.map(x=>x.psName))].join(', '))}</span>${cells(rows)}</summary>${days.length?days.map(d=>`<div class="ps-pivot-day"><span>${esc(d.date.split('-').reverse().join('/'))}</span><span>${esc([...new Set(d.rows.map(x=>x.psName))].join(', '))}</span>${cells(d.rows)}</div>`).join(''):'<p class="muted ps-no-days">No daily revenue available.</p>'}</details>`;}).join('')}</details>`).join('')}<div class="ps-pivot-total"><span>Grand total</span><span></span>${cells(total.rows)}</div></div></div>`;
}
